### PR TITLE
[WIP] feat: send SYN packet

### LINKED ISSUE #66: Send ACK packets

### PR DESCRIPTION
**Pull request by joao-vitor-souza**
Closes #66

### CODE REVIEW

**Comment by joao-vitor-souza** [comment]
> ## Hello Failed to import something No module named 'humanfriendly'
> Traceback (most recent call last):
> File "/home/overload/overload.py", line 50, in
> main()
> File "/home/overload/overload.py", line 34, in main
> with AttackMethod(
> NameError: name 'AttackMethod' is not defined. Did you mean: 'staticmethod'?
> root@ubuntu-s-4vcpu-8gb-ams3-01:/home/overload#
> Soryy Problem:S

This is not the right place to talk about issues. Open an Issue for that. Anyways, it seems that you haven't installed the dependencies. Run `make setup` before running `overload.py`.

**Comment by emir-ensar** [comment]
It didn't work, I sent you the articles I came across.   What should i do to make it work

**Comment by emir-ensar** [comment]
Installing Poetry...
------------------------------------------

Retrieving Poetry metadata

The latest version (1.2.2) is already installed.

------------------------------------------
Installing application dependencies...
------------------------------------------

make: poetry: No such file or directory
make: *** [Makefile:19: install] Error 127
root@ubuntu-s-4vcpu-8gb-ams3-01:/home/overload#

**Comment by emir-ensar** [comment]
https://prnt.sc/hfZGCqDBnRHi

**Comment by joao-vitor-souza** [comment]
> ## Installing Poetry...
> Retrieving Poetry metadata
> 
> The latest version (1.2.2) is already installed.
> 
> ## Installing application dependencies...
> make: poetry: No such file or directory make: *** [Makefile:19: install] Error 127 root@ubuntu-s-4vcpu-8gb-ams3-01:/home/overload#

That's weird, an Error 127 means that some file was not found, poetry is not finding `pyproject.toml` in this case. I've pushed it to main and you can `git pull origin main` to download the changes, then install the dependencies with `pip install -r requirements.txt`. Btw, I just ran overload here and it's working fine:



If you have some new problems, enter our [discord server](https://discord.com/invite/WKuk6aCqsj).

**Pull request merged**
